

  CREATE TABLE  "USERS" 
   (	
    "ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATEDATE" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(255), 
	"FIRSTNAME" VARCHAR2(255), 
	"LASTNAME" VARCHAR2(255), 
	"PASSWORD" VARCHAR2(255), 
	"SEX" VARCHAR2(255), 
	"UPDATEDDATE" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
   );
   
   CREATE TABLE VALIDUSERS 
(
  ID NUMBER(10) NOT NULL ,
  USERID VARCHAR2(120) NOT NULL ,
  PASSWORD VARCHAR2(120) NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO "VALIDUSERS" (ID, USERID, PASSWORD) VALUES ('1', 'abc', 'abc123');
INSERT INTO "VALIDUSERS" (ID, USERID, PASSWORD) VALUES ('2', 'def', 'def123');
INSERT INTO "VALIDUSERS" (ID, USERID, PASSWORD) VALUES ('3', 'fff', 'fff123');

commit;