

  CREATE TABLE  "USERS" 
   (	
    "ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATEDATE" TIMESTAMP (6), 
	"EMAIL" VARCHAR2(255), 
	"FIRSTNAME" VARCHAR2(255), 
	"LASTNAME" VARCHAR2(255), 
	"PASSWORD" VARCHAR2(255), 
	"SEX" VARCHAR2(255), 
	"UPDATEDDATE" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
   );